### ISSUE TITLE
[BUG] refreshToken错误

### ISSUE THREAD

**Issue by YosakuraTohu** [lc-cn/onebots#108]
OS: Arch Linux x86_64
Node: v21.5.0
OneBots: 0.4.50
Icqq: 0.6.8

icqq的协议版本指定为8.9.93
使用aPad扫码登录

```log
unhandledRejection TypeError: this.getT544 is not a function
at Client.tokenLogin (/home/kinare/Services/OneBots/node_modules/.pnpm/icqq@0.6.8/node_modules/icqq/lib/core/base-client.js:646:34)
at Client.refreshToken (/home/kinare/Services/OneBots/node_modules/.pnpm/icqq@0.6.8/node_modules/icqq/lib/core/base-client.js:1382:86)
at Client.refreshToken (/home/kinare/Services/OneBots/node_modules/.pnpm/icqq@0.6.8/node_modules/icqq/lib/core/base-client.js:521:35)
at heartbeatSuccess (/home/kinare/Services/OneBots/node_modules/.pnpm/icqq@0.6.8/node_modules/icqq/lib/core/base-client.js:1343:28)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by lc-cn** [comment]
前往icqq

**Comment by YosakuraTohu** [comment]
好的，谢谢
