### ISSUE TITLE
V11的合并转发再次无法发送

### ISSUE THREAD

**Issue by BennettChina** [lc-cn/onebots#137]
最新版的`onebots`和`icqqjs/icqq` 又出现了合并转发一直超时的问题，我这边用的时候好像 action 匹配不到就会一直超时，应该是 V11 没有像 V12 那样匹配不到 action 就抛出 404 异常的兜底。

**Comment by lc-cn** [comment]
请提供一下log日志和代码截图

**Comment by BennettChina** [comment]
> 请提供一下log日志和代码截图

```
[2024-03-25T15:43:03.763] [INFO] [OneBots:icqq-V11(**********)] -  收到ws消息： {"action":"send_private_msg","params":{"user_id":*******,"message":[{"type":"node","data":{"user_id":**********,"nickname":"派蒙","content":[{"type":"text","data":{"text":"测试内容1"}}]}},{"type":"node","data":{"user_id":**********,"nickname":"派蒙","content":[{"type":"text","data":{"text":"测试内容2"}}]}},{"type":"node","data":{"user_id":**********,"nickname":"派蒙","content":[{"type":"text","data":{"text":"测试内容3"}}]}}]},"echo":"lu6n54mjP9t86b"}
[2024-03-25T15:43:03.767] [ERROR] [OneBots:icqq-V11(**********)] - run send_private_msg with args:3 failed: TypeError: Cannot read properties of undefined (reading 'user_id')
    at IcqqAdapter.processMessages (/app/node_modules/onebots/lib/adapters/icqq/utils.js:14:35)
    at IcqqAdapter.sendPrivateMessage (/app/node_modules/onebots/lib/adapters/icqq/index.js:142:101)
    at IcqqAdapter.call (/app/node_modules/onebots/lib/adapters/icqq/index.js:192:36)
    at V11.sendPrivateMsg (/app/node_modules/onebots/lib/service/V11/action/friend.js:14:29)
    at V11.apply (/app/node_modules/onebots/lib/service/V11/index.js:594:53)
    at WebSocket.<anonymous> (/app/node_modules/onebots/lib/service/V11/index.js:420:38)
    at WebSocket.emit (node:events:517:28)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1209:20)
    at Receiver.emit (node:events:517:28)
    at /app/node_modules/ws/lib/receiver.js:608:16
```

顺便说下 Web 的 Console 好像不能选中复制日志？
