### ISSUE TITLE
WebConsole 无法选中日志及输入ticket报错

### ISSUE THREAD

**Issue by BennettChina** [lc-cn/onebots#143]
- WebConsole 无法选中日志并复制
- 输入滑动验证码后报错

第一个问题，`onebots@0.4.47` 这个版本是可以选中复制的。

第二个问题，以下是输入内容后的报错信息：

```
[2024-03-26T14:46:40.187] [MARK] [OneBots:icqq] - 请输入滑块验证返回的ticket
unhandledRejection TypeError: process_1.default.stdin.write is not a function
    at WebSocket.<anonymous> (/app/node_modules/onebots/lib/server/app.js:221:56)
    at WebSocket.emit (node:events:517:28)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1209:20)
    at Receiver.emit (node:events:517:28)
    at /app/node_modules/ws/lib/receiver.js:608:16
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by BennettChina** [comment]
`onebots` 版本用的最新的 `0.4.77`
