### ISSUE TITLE
Bug: V11 文本消息上报报错

### ISSUE THREAD

**Issue by BennettChina** [lc-cn/onebots#85]
node: `18.0.0`
npm: `8.6.0`

onebots@0.4.31
icqq@0.6.5
sqlite3@5.1.6

```
[2023-12-07T10:45:02.745] [INFO] [OneBots:icqq-V11(**********)] - ws客户端(/icqq/**********/V11)已连接
[2023-12-07T10:45:08.113] [INFO] [icqq] - recv from: [Private: **********(friend)] sss
unhandledRejection TypeError: Cannot read properties of undefined (reading 'text')
    at /bot/onebot/node_modules/onebots/lib/adapters/icqq/index.js:210:34
    at Array.map (<anonymous>)
    at IcqqAdapter.toCqcode (/bot/onebot/node_modules/onebots/lib/adapters/icqq/index.js:208:38)
    at V11.dispatch (/bot/onebot/node_modules/onebots/lib/service/V11/index.js:224:45)
    at IcqqAdapter.<anonymous> (/bot/onebot/node_modules/onebots/lib/service/V11/index.js:107:18)
    at IcqqAdapter.emit (node:events:527:28)
    at Client.<anonymous> (/bot/onebot/node_modules/onebots/lib/adapters/icqq/index.js:279:18)
    at Client.trip (/bot/onebot/node_modules/triptrap/lib/index.js:75:22)
    at Client.emit (/bot/onebot/node_modules/icqq/lib/core/base-client.js:245:21)
    at Client.em (/bot/onebot/node_modules/icqq/lib/client.js:720:18)
```

**Comment by lc-cn** [comment]
#104
